### ISSUE TITLE
Project discontinued?

### ISSUE THREAD

**Issue by SchumacherFM** [fritzpay/paymentd#151]
Hi,

sorry to ask here. What is the reason that the project has been discontinued?

What is the current status of the payment server? How much is missing to create a "MVP"?

Cyrill

**Comment by SchumacherFM** [comment]
Dead

**Comment by wongak** [comment]
Hi, sorry for the late reply. 
Yes, unfortunately we discontinued the project. We ceased operations of our startup some time ago.
Apart from our consulting work we were developing a payment/billing system which could run as a service or on premise. We decided to release the source code to the public with hopes that someone might find it useful.
The last items on our list were to create some documentation, explain our design decisions and plans for the project. Unfortunately noone got around that. Which means that we now have an abandoned project lying around here. But it's a shame. There were some good ideas in that project.

Wrt the state of the software:
We were very close to launch a proof of business/MVP with the exact state of the software you can find here. So you could call it a finished MVP.

After working another couple of years with Go, I would probably design some things differently, focus more on providing libraries instead of a full suite.

Could you elaborate more on your plans? Are you by chance interested in either using this or start maintaining this of something similar?

Cheers
